# Site settings
title: Marpa
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Libmarpa is an implementation of the Marpa parsing algorithm, which
  recognizes most practical grammers in linear time.
baseurl: "/marpa-site-temp/" # the subpath of your site, e.g. /blog/
url: "http://flaviut.github.io" # the base hostname & protocol for your site
github_username:  jekyll

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
